codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "20...100"
  ignore:
    - "hack"
    - "apis"
    - "**/*_types.go"
    - "**/*_moq.go"
    - "pkg/providers/types.go"
    - "pkg/client/fake"

  status:
    project:
      default:
        target: auto
        threshold: 0%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no