output:
  formats:
    - format: tab

linters:
  disable:
    - errcheck
    - ineffassign
    - unused
    - govet
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  modules-download-mode: readonly
  timeout: 5m