apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "BlobStorage",
          "metadata": {
            "labels": {
              "productName": "ProductName"
            },
            "name": "example-blobstorage"
          },
          "spec": {
            "applyImmediately": false,
            "secretRef": {
              "name": "example-blobstorage-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "Postgres",
          "metadata": {
            "labels": {
              "productName": "productName"
            },
            "name": "example-postgres"
          },
          "spec": {
            "secretRef": {
              "name": "example-postgres-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "PostgresSnapshot",
          "metadata": {
            "name": "example-postgressnapshot"
          },
          "spec": {
            "resourceName": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "Redis",
          "metadata": {
            "labels": {
              "productName": "productName"
            },
            "name": "example-redis"
          },
          "spec": {
            "applyImmediately": false,
            "secretRef": {
              "name": "example-redis-sec"
            },
            "tier": "development",
            "type": "REPLACE_ME"
          }
        },
        {
          "apiVersion": "integreatly.org/v1alpha1",
          "kind": "RedisSnapshot",
          "metadata": {
            "name": "example-redissnapshot"
          },
          "spec": {
            "resourceName": "REPLACE_ME"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    containerImage: quay.io/integreatly/cloud-resource-operator:v0.35.0
  name: cloud-resources.v0.35.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: BlobStorage
        name: blobstorages.integreatly.org
        version: v1alpha1
      - kind: Postgres
        name: postgres.integreatly.org
        version: v1alpha1
      - kind: PostgresSnapshot
        name: postgressnapshots.integreatly.org
        version: v1alpha1
      - kind: Redis
        name: redis.integreatly.org
        version: v1alpha1
      - kind: RedisSnapshot
        name: redissnapshots.integreatly.org
        version: v1alpha1
  description: Cloud Resource Operator description. TODO.
  displayName: Cloud Resource Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
                - persistentvolumes
              verbs:
                - '*'
            - apiGroups:
                - config.openshift.io
              resources:
                - infrastructures
                - networks
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - prometheusrules
              verbs:
                - '*'
          serviceAccountName: cloud-resource-operator
      deployments:
        - name: cloud-resource-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: cloud-resource-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: cloud-resource-operator
              spec:
                containers:
                  - command:
                      - cloud-resource-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: cloud-resource-operator
                      - name: TAG_KEY_PREFIX
                        value: integreatly.org/
                    image: quay.io/integreatly/cloud-resource-operator:v0.35.0
                    imagePullPolicy: Always
                    name: cloud-resource-operator
                    resources: {}
                serviceAccountName: cloud-resource-operator
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - get
                - update
                - patch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - ""
              resources:
                - configmaps
                - endpoints
                - events
                - persistentvolumeclaims
                - pods
                - pods/exec
                - secrets
                - services
                - services/finalizers
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - cloud-resource-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - cloudcredential.openshift.io
              resources:
                - credentialsrequests
              verbs:
                - '*'
            - apiGroups:
                - config.openshift.io
              resources:
                - '*'
                - authentications
                - builds
                - clusteroperators
                - featuregates
                - infrastructures
                - ingresses
                - networks
                - schedulers
              verbs:
                - '*'
            - apiGroups:
                - integreatly
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - integreatly.org
              resources:
                - '*'
                - postgres
                - postgressnapshots
                - redis
                - redissnapshots
                - smtpcredentialset
              verbs:
                - '*'
            - apiGroups:
                - integreatly.org
              resources:
                - blobstorages
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - integreatly.org
              resources:
                - blobstorages/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - prometheusrules
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - create
                - get
            - apiGroups:
                - operators.coreos.com
              resources:
                - catalogsources
              verbs:
                - get
                - patch
                - update
          serviceAccountName: cloud-resource-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - cloud-resource-operator
  links:
    - name: Cloud Resource Operator
      url: https://cloud-resource-operator.domain
  maintainers:
    - email: your@email.com
      name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.35.0
  skips:
    - cloud-resources.v0.34.0
  replaces: cloud-resources.v0.33.0
