# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/integreatly.org_blobstorages.yaml
- bases/integreatly.org_postgres.yaml
- bases/integreatly.org_postgressnapshots.yaml
- bases/integreatly.org_redis.yaml
- bases/integreatly.org_redissnapshots.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_blobstorages.yaml
#- patches/webhook_in_postgres.yaml
#- patches/webhook_in_postgressnapshots.yaml
#- patches/webhook_in_redis.yaml
#- patches/webhook_in_redissnapshots.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_blobstorages.yaml
#- patches/cainjection_in_postgres.yaml
#- patches/cainjection_in_postgressnapshots.yaml
#- patches/cainjection_in_redis.yaml
#- patches/cainjection_in_redissnapshots.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
