FROM registry.access.redhat.com/ubi9/go-toolset:1.25.9

# Switch to root to install tools
USER root

ENV OPERATOR_SDK_VERSION=v1.42.0
ENV MOQ_VERSION=v0.5.2

ENV GOPATH=/go
ENV GOBIN=$GOPATH/bin
ENV PATH=$GOBIN:$PATH

# install operator-sdk (from git with no history and only the tag)
RUN mkdir -p $GOPATH/src/github.com/operator-framework \
    && cd $GOPATH/src/github.com/operator-framework \
    && git clone --depth 1 -b $OPERATOR_SDK_VERSION https://github.com/operator-framework/operator-sdk \
    && cd operator-sdk \
    && go mod vendor \
    && go mod tidy \
    && make install \
    && chmod -R 0777 $GOPATH \
    && rm -rf $GOPATH/.cache

# install gosec
RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin v2.21.4

# Ensure proper permissions for Go cache and workspace, then switch back to default user
RUN mkdir -p /opt/app-root/src/.cache && \
    chmod -R 777 /opt/app-root/src/.cache && \
    chmod -R 777 /opt/app-root/src && \
    chmod -R 777 /go

# Switch back to default user
USER 1001